# api:
# Initial Replicas
replicaCount: 1
# Docker Settings.
image:
    repository: ghcr.io/the-bob/fast-api
    pullPolicy: Always
    tag: latest_main
# Auto-Scalling Settings via HPA
# autoscaling:
#     enabled: true
#     targetCPUUtilizationPercentage: 90
#     targetMemoryUtilizationPercentage: 90
#     maxReplicas: 5
#     minReplicas: 1
# Pod Resources
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
# Ingress
ingress:
    enabled: true
    hosts:
      - host: api.dev.acmecorpresearch.com
        paths:
          - path: /
            pathType: Prefix
            port:
              number: 80
      - host: api.dev.acmecorpresearch.com
        paths:
          - path: /*
            pathType: Prefix
            port:
              number: 80
    annotations:
      external-dns.alpha.kubernetes.io/hostname: api.dev.acmecorpresearch.com
      external-dns.alpha.kubernetes.io/ttl: "60"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/ingress.allow-http: "false"
      # nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.org/redirect-to-https: "true"
      nginx.org/client-body-buffer-size: 900m
      

# Config Map
config:
    values:
      MYSQL_USER: acmecorp
      MYSQL_HOST: acmecorp.crgjwgjb5aut.eu-north-1.rds.amazonaws.com
      MYSQL_DB: acmecorp
      MYSQL_PORT: "3306"
      MYSQL_PASS: "adminPa55w0rd"
